# Generated by Django 5.0.1 on 2025-07-16 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_appointment_medicalrecord_prescription_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='rag_document',
        ),
        migrations.RemoveField(
            model_name='embeddingprocessinglog',
            name='rag_document',
        ),
        migrations.RemoveField(
            model_name='embeddingprocessinglog',
            name='user',
        ),
        migrations.CreateModel(
            name='DocumentEmbedding',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='data_management.filemetadata')),
                ('total_chunks', models.IntegerField()),
                ('embedding_model', models.CharField(max_length=100)),
                ('processing_status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_embeddings',
                'indexes': [models.Index(fields=['processing_status'], name='document_em_process_8b00eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_text_preview', models.CharField(max_length=500)),
                ('embedding_vector', models.TextField()),
                ('vector_dimension', models.IntegerField()),
                ('document_embedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='data_management.documentembedding')),
            ],
            options={
                'db_table': 'embedding_chunks',
            },
        ),
        migrations.DeleteModel(
            name='ChunkEmbedding',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
        migrations.DeleteModel(
            name='EmbeddingProcessingLog',
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=models.Index(fields=['document_embedding', 'chunk_index'], name='embedding_c_documen_bb2e9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='embeddingchunk',
            unique_together={('document_embedding', 'chunk_index')},
        ),
    ]
