# Generated by Django 4.2.11 on 2025-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_alter_documentchunk_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='embeddingchunk',
            old_name='chunk_text_preview',
            new_name='chunk_text',
        ),
        migrations.AlterField(
            model_name='embeddingchunk',
            name='chunk_text',
            field=models.TextField(),
        ),
    ]