# Generated by Django 5.2.4

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_remove_embedding_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGEmbedding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='data_management.ragdocument')),
            ],
            options={
                'db_table': 'rag_embeddings',
                'ordering': ['document', 'chunk_index'],
                'indexes': [
                    models.Index(fields=['document', 'chunk_index'], name='data_manage_documen_0e7d8c_idx'),
                    models.Index(fields=['created_at'], name='data_manage_created_8c9d14_idx'),
                ],
                'unique_together': {('document', 'chunk_index')},
            },
        ),
        migrations.CreateModel(
            name='RAGEmbeddingJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_jobs', to='data_management.ragdocument')),
            ],
            options={
                'db_table': 'rag_embedding_jobs',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='data_manage_status_2a7b8c_idx'),
                    models.Index(fields=['document'], name='data_manage_documen_4f5d9a_idx'),
                ],
            },
        ),
    ]