# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_ragembedding_ragembeddingjob'),
    ]

    operations = [
        migrations.RunSQL(
            # Create PGVector extension if not exists
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;"
        ),
        migrations.RunSQL(
            # Add vector column for embeddings
            sql="""
                ALTER TABLE rag_embeddings 
                ADD COLUMN embedding_vector vector(1536);
                
                CREATE INDEX rag_embeddings_vector_idx 
                ON rag_embeddings 
                USING ivfflat (embedding_vector vector_cosine_ops)
                WITH (lists = 100);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS rag_embeddings_vector_idx;
                ALTER TABLE rag_embeddings 
                DROP COLUMN IF EXISTS embedding_vector;
            """,
        ),
    ]