# Generated by Django 5.2.4 on 2025-07-29 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_add_pgvector_column'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ragembedding',
            new_name='rag_embeddi_documen_65f35d_idx',
            old_name='data_manage_documen_0e7d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='ragembedding',
            new_name='rag_embeddi_created_0cd1b2_idx',
            old_name='data_manage_created_8c9d14_idx',
        ),
        migrations.RenameIndex(
            model_name='ragembeddingjob',
            new_name='rag_embeddi_status_a4b581_idx',
            old_name='data_manage_status_2a7b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='ragembeddingjob',
            new_name='rag_embeddi_documen_3dd1e5_idx',
            old_name='data_manage_documen_4f5d9a_idx',
        ),
    ]
