# Generated by Django 5.0.1 on 2025-08-05 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_rename_data_manage_documen_0e7d8c_idx_rag_embeddi_documen_65f35d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='clinicians', to='data_management.cancertype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clinicians',
            },
        ),
    ]
