# Generated by Django 5.0.1 on 2025-08-05 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_clinician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clinician',
            name='specialization',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinicians', to='data_management.cancertype'),
        ),
    ]
