# Generated by Django 5.2.4 on 2025-08-06 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_make_clinician_fields_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='data_management.clinician')),
                ('cancer_subtype', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='patient_assignments', to='data_management.cancertype')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='data_management.patient')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_assignments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_assignments',
                'indexes': [models.Index(fields=['patient'], name='patient_ass_patient_198f1a_idx'), models.Index(fields=['assigned_clinician'], name='patient_ass_assigne_de8d1d_idx'), models.Index(fields=['cancer_subtype'], name='patient_ass_cancer__644e1e_idx')],
            },
        ),
    ]
