# Generated by Django 5.0.1 on 2025-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_add_patient_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_record_types',
                'ordering': ['type_name'],
            },
        ),
    ]
