# Generated by Django 5.0.1 on 2025-08-08 05:54

from django.db import migrations


def populate_medical_record_types(apps, schema_editor):
    MedicalRecordType = apps.get_model('data_management', 'MedicalRecordType')
    
    record_types = [
        'Laboratory Results',
        'Imaging Reports',
        'Pathology Reports',
        'Consultation Notes',
        'Procedure Reports',
        'Medication History',
        'Treatment Plans',
        'Diagnostic Tests',
        'Surgical Reports',
        'Radiology Reports',
        'Biopsy Reports',
        'Chemotherapy Records',
        'Radiation Therapy Records',
        'Progress Notes',
        'Discharge Summaries',
        'Admission Records',
        'Physical Examination',
        'Immunization Records',
        'Allergy Documentation',
        'Clinical Assessments',
    ]
    
    for type_name in record_types:
        MedicalRecordType.objects.create(type_name=type_name)


def reverse_populate_medical_record_types(apps, schema_editor):
    MedicalRecordType = apps.get_model('data_management', 'MedicalRecordType')
    MedicalRecordType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_add_medical_record_type'),
    ]

    operations = [
        migrations.RunPython(populate_medical_record_types, reverse_populate_medical_record_types),
    ]
