# Generated by Django 5.0.1 on 2025-08-08 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_populate_medical_record_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_record', serialize=False, to='data_management.filemetadata')),
                ('medical_record_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_records', to='data_management.medicalrecordtype')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='data_management.patient')),
            ],
            options={
                'db_table': 'medical_records',
                'indexes': [models.Index(fields=['patient'], name='medical_rec_patient_98186b_idx'), models.Index(fields=['medical_record_type'], name='medical_rec_medical_7b8edc_idx')],
                'unique_together': {('file', 'patient', 'medical_record_type')},
            },
        ),
    ]
