# Generated by Django 5.0.1 on 2025-08-08 07:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_add_medical_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_access_key', models.TextField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'medical_record_access',
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_encryption_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['-created_at'], name='medical_rec_created_b96424_idx'),
        ),
        migrations.AddField(
            model_name='medicalrecordaccess',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_granted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecordaccess',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='data_management.medicalrecord'),
        ),
        migrations.AddField(
            model_name='medicalrecordaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicalrecordaccess',
            index=models.Index(fields=['user', '-granted_at'], name='medical_rec_user_id_62691f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordaccess',
            index=models.Index(fields=['medical_record', 'user'], name='medical_rec_medical_36c4d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecordaccess',
            unique_together={('medical_record', 'user')},
        ),
    ]
