# Generated by Django 5.2.4 on 2025-10-10 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_add_medical_record_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_history', to='data_management.chatsession')),
            ],
            options={
                'db_table': 'suggested_history',
                'indexes': [models.Index(fields=['session', '-created_at'], name='suggested_h_session_da46ff_idx')],
                'unique_together': {('session', 'text')},
            },
        ),
        migrations.CreateModel(
            name='SuggestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding_json', models.JSONField(blank=True, null=True)),
                ('cancer_type', models.ForeignKey(db_column='cancer_type_id', on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_templates', to='data_management.cancertype')),
            ],
            options={
                'db_table': 'suggestion_templates',
                'indexes': [models.Index(fields=['cancer_type'], name='suggestion__cancer__be362d_idx')],
                'unique_together': {('cancer_type', 'text')},
            },
        ),
    ]
